services:
  app:
    image: ghcr.io/korotkov-s/under-meetup:latest
    container_name: under-meetup
    restart: always
    ports:
      - '3333:3333'
    env_file: .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - adonis-network

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=adonis
      - MYSQL_DATABASE=undermeetup
      - MYSQL_USER=adonis
      - MYSQL_PASSWORD=adonis
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - adonis-network

volumes:
  mariadb_data:

networks:
  adonis-network:
    driver: bridge
