version: '3.8'

services:
  undermeetup:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - '3333:3333'
    environment:
      - TZ=UTC
      - PORT=3333
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=cPO4rQKcrRFeE5dS5lfF5n3Ng_4hY97S
      - NODE_ENV=development
      - SESSION_DRIVER=cookie
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USER=adonis
      - DB_PASSWORD=adonis
      - DB_DATABASE=undermeetup
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - adonis-network

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=adonis
      - MYSQL_DATABASE=undermeetup
      - MYSQL_USER=adonis
      - MYSQL_PASSWORD=adonis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '3307:3306'
    networks:
      - adonis-network

volumes:
  postgres_data:

networks:
  adonis-network:
    driver: bridge
