version: '3.8'

services:
  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=adonis
      - MYSQL_DATABASE=undermeetup
      - MYSQL_USER=adonis
      - MYSQL_PASSWORD=adonis
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - adonis-network

volumes:
  mariadb_data:

networks:
  adonis-network:
    driver: bridge
