version: '3.8'

services:
  app:
    build: .
    ports:
      - '3333:3333'
    env_file: .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    networks:
      - adonis-network

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=adonis
      - POSTGRES_PASSWORD=adonis
      - POSTGRES_DB=undermeetup
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5444:5444'
    networks:
      - adonis-network

volumes:
  postgres_data:

networks:
  adonis-network:
    driver: bridge
