name: Build & Push Adonis v6 App

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install Yarn 4.9.2
        run: |
          corepack enable
          yarn set version 4.9.2 --only-if-needed
          yarn install

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repo owner and name to lowercase
        run: |
          echo "IMAGE=ghcr.io/${{ github.repository_owner }}/under-meetup" >> $GITHUB_ENV
          echo "IMAGE_LC=ghcr.io/${{ github.repository_owner | toLower }}/under-meetup" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/korotkov-s/under-meetup:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/korotkov-s/under-meetup:latest
